server:
    module-config: "validator cachedb iterator"
    num-threads: 8

    serve-expired: yes
    serve-expired-ttl: 86400
    serve-expired-client-timeout: 0
    # cache-min-ttl: 300

    msg-cache-size: 256m
    rrset-cache-size: 512m
    neg-cache-size: 64m
    key-cache-size: 128m
    infra-cache-numhosts: 100000

    num-queries-per-thread: 4096
    outgoing-range: 8192
    jostle-timeout: 200

    prefetch: yes
    prefetch-key: yes

    log-time-ascii: yes
    # log-queries: yes
    # log-replies: yes
    extended-statistics: yes

remote-control:
    control-enable: yes
    control-use-cert: no

cachedb:
    backend: "redis"
    redis-server-host: valkey-unbound
    redis-server-port: 6379
    redis-expire-records: no
