server:
    module-config: "validator cachedb iterator"
    # serve-expired: yes
    # serve-expired-ttl: 86400
    # serve-expired-client-timeout: 0
    # cache-min-ttl: 300
    prefetch: yes
    msg-cache-size: 64m
    rrset-cache-size: 128m

cachedb:
    backend: "redis"
    redis-server-host: valkey
    redis-server-port: 6379
    redis-expire-records: no
