import { nvmeMount } from "~lib/service/mounts";
import { ContainerService } from "~lib/service/service";
import { getEnv } from "~lib/env";

export const minecraftService = new ContainerService(
  "minecraft",
  {
    image: "itzg/minecraft-server:java21-jdk",
    servicePort: 8804,
    subdomain: "mc",
    ports: [25565, 7091, 24454],
    mounts: [nvmeMount("minecraft", "/data")],
    envs: {
      EULA: true,
      // "TYPE=MODRINTH",
      // "MODRINTH_MODPACK=6p1xQ7wU",
      // "MODRINTH_DEFAULT_EXCLUDE_INCLUDES=",
      TYPE: "AUTO_CURSEFORGE",
      CF_API_KEY: getEnv("CURSEFORGE_API_KEY"),
      CF_SLUG: "bcg",
      CF_PARALLEL_DOWNLOADS: 16,
      CF_EXCLUDE_INCLUDE_FILE: "",
      CURSEFORGE_FILES: 508727,
      PLAN_DATA_GATHERING_ACCEPT_GEOLITE2_EULA: true, // y dis no work (https://github.com/plan-player-analytics/Plan/commit/24a8c75b67986e90acfc5abeed29328d8cc9407a)
      MEMORY: "16G",
      JVM_XX_OPTS:
        "-XX:+UseZGC -XX:AllocatePrefetchStyle=1 -XX:+UseLargePages -XX:LargePageSizeInBytes=2m -Xlog:gc+init",
      ENABLE_ROLLING_LOGS: true,
      ENABLE_JMX: true,
      JMX_HOST: "mc.bas.sh",
      LOG_TIMESTAMP: true,
      // "STOP_SERVER_ANNOUNCE_DELAY=10",
      DUMP_SERVER_PROPERTIES: true,
      MOTD: "                   \u00A7f\u00A7l／人◕ ‿‿ ◕人＼\u00A7r\n \u00A7a%MODPACK_NAME%\u00A7r \u00A7cversion \u00A7a%MODPACK_VERSION%",
      DIFFICULTY: "normal",
      OPS: "basw",
      ICON: "https://i.bas.sh/kyubey.jpg",
      OVERRIDE_ICON: true,
      ENABLE_QUERY: true,
      MAX_PLAYERS: 100,
      FORCE_GAMEMODE: true,
      ENABLE_COMMAND_BLOCK: true,
      MAX_BUILD_HEIGHT: 1024,
      VIEW_DISTANCE: 32,
      SERVER_NAME: "／人◕ ‿‿ ◕人＼",
      PLAYER_IDLE_TIMEOUT: 0,
      SIMULATION_DISTANCE: 12,
      SPAWN_PROTECTION: 0,
      SYNC_CHUNK_WRITES: false,
      RCON_PASSWORD: getEnv("RCON_PASSWORD"),
    },
    capabilities: ["SYS_ADMIN"],
    stdinOpen: true,
    tty: true,
    destroyGraceSeconds: 60,
    // stopSignal: "SIGINT",
  },
  {
    // ignoreChanges: (await mcHasOnlinePlayers("minecraft")) ? ["*"] : [],
  },
);
