import { nvmeMount, ssdcacheMount, mount } from "~lib/service/mounts";
import { ContainerService } from "~lib/service/service";
import { getEnv } from "~lib/env";

const minecraftTeenaService = new ContainerService(
  "minecraft-teena",
  {
    // image: "itzg/minecraft-server:java24-graalvm",
    image: "itzg/minecraft-server",
    // servicePort: 8804,
    servicePort: 80,
    subdomain: "gigasigmas",
    ports: [25566, "24455/udp"],
    otherServicePorts: {
      // "polymer-sigmas": 25567,
      // // "map.akio": 8123,
      // map: 8100,
    },
    mounts: [
      nvmeMount("minecraft-teena", "/data"),
      ssdcacheMount("sync/minecraft", "/sync"),
      mount("/dev/hugepages"),
    ],
    envs: {
      EULA: true,
      SERVER_PORT: 25566,
      LEVEL: "skibidisigmy",
      TYPE: "AUTO_CURSEFORGE",
      CF_MODPACK_ZIP: "/sync/Jedziemy w bieszczady.zip",
      CF_API_KEY: getEnv("CURSEFORGE_API_KEY"),
      CF_PARALLEL_DOWNLOADS: 16,
      CF_SLUG: "jedziemy_w_bieszczady",
      CURSEFORGE_FILES: [
        "alternate-current",
        "distant-horizons",
        "servercore",
        "vanishmod",
        "fullstack-watchdog",
        "modernfix",
        "canary",
        "better-chunk-loading-forge-fabric",
        "connectivity",
        "chunk-sending-forge-fabric",
        "cupboard",
        "leaky",
        "almanac-lib",
        "let-me-despawn",
        "alltheleaks",
        // "recipe-essentials-forge-fabric",
        "no-chat-reports",
        // "attributefix",
        // "structure-essentials-forge-fabric",
        "mixintrace-resmithed",
        "placebo",
        "fastsuite",
        // "kubejs",
        // "chunky-pregenerator-forge",
        "noisium",
        // "placebo",
        // "architectury-api",
        // "rhino",
        // once itzg adds support
        // "fabric:axiomtool"
        // "fabric:c2me"
        "craterlib",
        "simple-discord-link-bot-forge-fabric-spigot",
        "im-fast",
        "modlistobserver",
        "inv-view-forge",
      ],
      CF_EXCLUDE_MODS: ["itemphysic-lite", "blur-forge"],
      CF_FORCE_SYNCHRONIZE: true,
      // CF_FORCE_INCLUDE_MODS: "appleskin",
      CF_EXCLUDE_INCLUDE_FILE: "",
      MODRINTH_PROJECTS: [
        // "plan",
        // "memoryleakfix",
        // "chunky-player-pause",
        // "inv-view-forge",
        //   // world rendering
        //   "c2me-fabric",
        //   // performance
        //   "lithium",
        //   "scalablelux",
        //   "ferrite-core",
        //   "noisium",
        //   "spark",
        //   "pandaantidupe",
        //   "clumps", // does ServerCore already cover this?
        //   "alternate-current",
        //   "lmd",
        //
        //   // admin stuff
        //   "vanilla-refresh",
        //   "axiom",
        //   "invview",
        //   "better-fabric-console",
        //   "configured", // TODO: configure
        //   "nbt-copy",
        //   "too-fast",
        // "stackdeobf",
        // "codecium",
        //   "chunky",
        //   "chunky-player-pause",
        //   "maintenancemode",
        //   "patched",
        //   "entity-information",
        // "simple-server-restart",
        //   "worldgen-devtools",
        //   "noconsolespam",
        //
        //   // networking
        //   "no-chat-reports",
        //   "viafabric",
        //   "viabackwards",
      ],
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required",
      MODRINTH_ALLOWED_VERSION_TYPE: "alpha",
      PLAN_DATA_GATHERING_ACCEPT_GEOLITE2_EULA: true, // y dis no work (https://github.com/plan-player-analytics/Plan/commit/24a8c75b67986e90acfc5abeed29328d8cc9407a)
      MEMORY: "16G",
      JVM_XX_OPTS:
        // "-XX:+UseZGC -XX:AllocatePrefetchStyle=1 -XX:+UseLargePages -XX:LargePageSizeInBytes=2m -Xlog:gc+init",
        "-XX:+UseZGC -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:+UseTransparentHugePages",
      ENABLE_ROLLING_LOGS: true,
      ENABLE_JMX: true,
      JMX_HOST: "gigasigmas.bas.sh",
      LOG_TIMESTAMP: true,
      STOP_SERVER_ANNOUNCE_DELAY: 10,
      DUMP_SERVER_PROPERTIES: true,
      MOTD: "\u00a7r                \u00a74\u00a7l\u00a7nGIGA\u00a7r\n\u00a74\u00a7l              \u00a76Sigmas",
      DIFFICULTY: "normal",
      OPS: ["basw", "PingwinWMeloniku"],
      ICON: "icon.jpg",
      OVERRIDE_ICON: true,
      ENABLE_QUERY: true,
      MAX_PLAYERS: 69,
      FORCE_GAMEMODE: false,
      ENABLE_COMMAND_BLOCK: true,
      MAX_BUILD_HEIGHT: 1024,
      VIEW_DISTANCE: 16,
      SERVER_NAME: "GigaSigmas",
      PLAYER_IDLE_TIMEOUT: 0,
      SIMULATION_DISTANCE: 8,
      SPAWN_PROTECTION: 0,
      SYNC_CHUNK_WRITES: false,
      ENFORCE_SECURE_PROFILE: false,
      BROADCAST_CONSOLE_TO_OPS: false,
      BROADCAST_RCON_TO_OPS: false,
      ENABLE_WHITELIST: true,
      WHITELIST: ["basw", "PingwinWMeloniku"],
      ALLOW_FLIGHT: true,
      RCON_PASSWORD: getEnv("RCON_PASSWORD"),
    },
    capabilities: ["SYS_ADMIN"],
    stdinOpen: true,
    tty: true,
    destroyGraceSeconds: 60,
    // stopSignal: "SIGINT",
  },
  {
    // ignoreChanges: (await mcHasOnlinePlayers("minecraft-teena")) ? ["*"] : [],
  },
);
